title: Hello, world! I'm Gabriel Przybysz
description: > # this means to ignore newlines until "baseurl:"
  I'm 18 years old, I started in the technology industry at 14. Passionate about programming, math and infosec.

permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://gabrielprzybysz.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gabriel Przybysz # add your name
author-img: gabriel-przybysz.jpg # add your photo
about-author: I am a backend dev. Always hungry to keep learning. # add description
social-twitter: GabrielPrzybys3
social-facebook: gabriel.junior.12
social-github: GabrielPrzybysz 
social-linkedin: gabriel-przybysz-864b42163
social-email: gabrielgprzy@gmail.com

# Disqus
discus-identifier: GabeBlog # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
